spring:
  config:
    import: optional:configserver:http://localhost:1012
  cloud:
    config:
      label: main

app:
  feign:
    exchange-service:
      url: ${APP_FEIGN_EXCHANGE_SERVICE_URL:http://localhost:1016/}
    notification-service:
      url: ${APP_FEIGN_NOTIFICATION_SERVICE_URL:http://localhost:1018/}