server:
  port: ${SERVER_PORT:1019}
spring:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI:http://localhost:8888/realms/bankapp}
        registration:
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: Xih8xBTW8WuoJvBRFzuhQ8DXbxdONfec
            scope:
              - profile
            client-authentication-method: client_secret_post
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: bankapp
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
      spring.json.use.type.headers: false
      spring.json.value.default.type: org.company.exchangegenerator.dto.CurrencyDto
      spring.kafka.observation.enabled: true
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    liquibase:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
app:
  feign:
    exchange-service:
      url: ${APP_FEIGN_EXCHANGE_SERVICE_URL:http://localhost:1016/exchange}

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.actuate: INFO
    org.example: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"