server:
  port: ${SERVER_PORT:1018}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5438/bank?currentSchema=notification}
    username: ${DB_USERNAME:yandex}
    password: ${DB_PASSWORD:yandex}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        observability.enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: notification
  thymeleaf:
    encoding: UTF-8
  liquibase:
    change-log: classpath:/db/changelog/rootChangeLog.xml
    liquibase-schema: public
    default-schema: notification
    parameters:
      schemaName: notification
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5438/bank?currentSchema=notification}
    user: ${DB_USERNAME:yandex}
    password: ${DB_PASSWORD:yandex}
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI:http://localhost:8888/realms/bankapp}
        registration:
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: Xih8xBTW8WuoJvBRFzuhQ8DXbxdONfec
            scope:
              - profile
            client-authentication-method: client_secret_post
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: bankapp
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
      spring.json.use.type.headers: false
      spring.json.value.default.type: org.company.notification.dto.NotificationDto
      spring.kafka.observation.enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    liquibase:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
logging:
  level:
    org.springframework.boot.actuate: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.web: DEBUG
    org.company.notification: DEBUG
    liquibase: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  client:
    enabled: false