apiVersion: v2
name: bank
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: front-service
    version: 0.1.0
    repository: "file://charts/front-service"
    condition: front-service.enabled

  - name: account-service
    version: 0.1.0
    repository: "file://charts/account-service"
    condition: account-service.enabled

  - name: blocker-service
    version: 0.1.0
    repository: "file://charts/blocker-service"
    condition: blocker-service.enabled

  - name: cash-service
    version: 0.1.0
    repository: "file://charts/cash-service"
    condition: cash-service.enabled

  - name: exchange-service
    version: 0.1.0
    repository: "file://charts/exchange-service"
    condition: exchange-service.enabled

  - name: exchange-generator-service
    version: 0.1.0
    repository: "file://charts/exchange-generator-service"
    condition: exchange-generator-service.enabled

  - name: notification-service
    version: 0.1.0
    repository: "file://charts/notification-service"
    condition: notification-service.enabled

  - name: transfer-service
    version: 0.1.0
    repository: "file://charts/transfer-service"
    condition: transfer-service.enabled

  - name: keycloak-service
    version: 0.1.0
    repository: "file://charts/keycloak-service"
    condition: keycloak-service.enabled

  - name: postgresql
    version: 14.2.3
    repository: https://charts.bitnami.com/bitnami
    alias: shared-db
    condition: shared-db.enabled

  - name: kafka
    version: 32.4.3
    repository: https://charts.bitnami.com/bitnami
    alias: app-kafka
    condition: app-kafka.enabled

  - name: zookeeper
    version: 13.8.7
    repository: https://charts.bitnami.com/bitnami
    alias: app-zookeeper
    condition: app-kafka.enabled

  - name: zipkin-service
    version: 0.1.0
    repository: "file://charts/zipkin-service"
    condition: zipkin-service.enabled

  - name: prometheus-service
    version: 0.1.0
    repository: "file://charts/prometheus-service"
    condition: prometheus-service.enabled

  - name: grafana-service
    version: 0.1.0
    repository: "file://charts/grafana-service"
    condition: grafana-service.enabled

  - name: elasticsearch-service
    version: 0.1.0
    repository: "file://charts/elasticsearch-service"
    condition: elasticsearch-service.enabled

  - name: kibana-service
    version: 0.1.0
    repository: "file://charts/kibana-service"
    condition: kibana-service.enabled

  - name: logstash-service
    version: 0.1.0
    repository: "file://charts/logstash-service"
    condition: logstash-service.enabled