{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash-service.fullname" . }}
  labels:
    {{- include "logstash-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.beats }}
      targetPort: beats
      protocol: TCP
      name: beats
    - port: {{ .Values.service.ports.monitoring }}
      targetPort: monitoring
      protocol: TCP
      name: monitoring
  selector:
    {{- include "logstash-service.selectorLabels" . | nindent 4 }}
{{- end }}
