{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch-service.fullname" . }}
  labels:
    {{- include "elasticsearch-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.transportPort }}
      targetPort: transport
      protocol: TCP
      name: transport
  selector:
    {{- include "elasticsearch-service.selectorLabels" . | nindent 4 }}
{{- end }}
